// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraCuu.Domain;

namespace TraCuu.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200319223118_tracuu")]
    partial class tracuu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TraCuu.Domain.ChiNhanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChiNhanhID");

                    b.Property<string>("TenChiNhanh");

                    b.HasKey("Id");

                    b.ToTable("ChiNhanh");
                });

            modelBuilder.Entity("TraCuu.Domain.ChiTietTKCKH", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("ChiNhanhID")
                        .HasColumnType("decimal(4, 0)");

                    b.Property<decimal>("LaiSuat")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgayDenHan");

                    b.Property<DateTime>("NgayGui");

                    b.Property<DateTime>("NgayTaiTuc");

                    b.Property<decimal>("SoDu")
                        .HasColumnType("decimal(14, 0)");

                    b.Property<decimal>("SoTienGui")
                        .HasColumnType("decimal(14, 0)");

                    b.Property<decimal>("ThoiHan")
                        .HasColumnType("decimal(4, 0)");

                    b.Property<bool>("ToChuc");

                    b.HasKey("Id");

                    b.ToTable("ChiTietTKCKH");
                });
#pragma warning restore 612, 618
        }
    }
}
